// Generated by gencpp from file my_robot_msgs/CountUntilResult.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_COUNTUNTILRESULT_H
#define MY_ROBOT_MSGS_MESSAGE_COUNTUNTILRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct CountUntilResult_
{
  typedef CountUntilResult_<ContainerAllocator> Type;

  CountUntilResult_()
    : counted_untill(0)  {
    }
  CountUntilResult_(const ContainerAllocator& _alloc)
    : counted_untill(0)  {
  (void)_alloc;
    }



   typedef int64_t _counted_untill_type;
  _counted_untill_type counted_untill;





  typedef boost::shared_ptr< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> const> ConstPtr;

}; // struct CountUntilResult_

typedef ::my_robot_msgs::CountUntilResult_<std::allocator<void> > CountUntilResult;

typedef boost::shared_ptr< ::my_robot_msgs::CountUntilResult > CountUntilResultPtr;
typedef boost::shared_ptr< ::my_robot_msgs::CountUntilResult const> CountUntilResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::CountUntilResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::CountUntilResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::CountUntilResult_<ContainerAllocator2> & rhs)
{
  return lhs.counted_untill == rhs.counted_untill;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::CountUntilResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::CountUntilResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6c3b2773d059533fd3e6200a4b10883";
  }

  static const char* value(const ::my_robot_msgs::CountUntilResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6c3b2773d059533ULL;
  static const uint64_t static_value2 = 0xfd3e6200a4b10883ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/CountUntilResult";
  }

  static const char* value(const ::my_robot_msgs::CountUntilResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"int64 counted_untill\n"
;
  }

  static const char* value(const ::my_robot_msgs::CountUntilResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.counted_untill);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountUntilResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::CountUntilResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::CountUntilResult_<ContainerAllocator>& v)
  {
    s << indent << "counted_untill: ";
    Printer<int64_t>::stream(s, indent + "  ", v.counted_untill);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_COUNTUNTILRESULT_H
