// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountUntilGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.count_untill = null;
      this.wait_untill = null;
    }
    else {
      if (initObj.hasOwnProperty('count_untill')) {
        this.count_untill = initObj.count_untill
      }
      else {
        this.count_untill = 0;
      }
      if (initObj.hasOwnProperty('wait_untill')) {
        this.wait_untill = initObj.wait_untill
      }
      else {
        this.wait_untill = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountUntilGoal
    // Serialize message field [count_untill]
    bufferOffset = _serializer.int64(obj.count_untill, buffer, bufferOffset);
    // Serialize message field [wait_untill]
    bufferOffset = _serializer.float64(obj.wait_untill, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountUntilGoal
    let len;
    let data = new CountUntilGoal(null);
    // Deserialize message field [count_untill]
    data.count_untill = _deserializer.int64(buffer, bufferOffset);
    // Deserialize message field [wait_untill]
    data.wait_untill = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/CountUntilGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '27ab67758cea5a96e42d3ec78a58584d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    int64 count_untill
    float64 wait_untill
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountUntilGoal(null);
    if (msg.count_untill !== undefined) {
      resolved.count_untill = msg.count_untill;
    }
    else {
      resolved.count_untill = 0
    }

    if (msg.wait_untill !== undefined) {
      resolved.wait_untill = msg.wait_untill;
    }
    else {
      resolved.wait_untill = 0.0
    }

    return resolved;
    }
};

module.exports = CountUntilGoal;
