// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountUntilResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.counted_untill = null;
    }
    else {
      if (initObj.hasOwnProperty('counted_untill')) {
        this.counted_untill = initObj.counted_untill
      }
      else {
        this.counted_untill = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountUntilResult
    // Serialize message field [counted_untill]
    bufferOffset = _serializer.int64(obj.counted_untill, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountUntilResult
    let len;
    let data = new CountUntilResult(null);
    // Deserialize message field [counted_untill]
    data.counted_untill = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/CountUntilResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd6c3b2773d059533fd3e6200a4b10883';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    int64 counted_untill
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountUntilResult(null);
    if (msg.counted_untill !== undefined) {
      resolved.counted_untill = msg.counted_untill;
    }
    else {
      resolved.counted_untill = 0
    }

    return resolved;
    }
};

module.exports = CountUntilResult;
